apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: test-k8s-python
  namespace: argocd
spec:
  project: default
  source:
    repoURL: 'https://github.com/luca-andrei51003/Docker/'
    targetRevision: main
    path: python-k8s/k8s
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: test-k8s-python
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
