apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-k8s-python
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test-k8s-python
  template:
    metadata:
      labels:
        app: test-k8s-python
    spec:
      containers:
        - name: test-k8s-python
          image: test-k8s-python:latest
          imagePullPolicy: Always
          ports:
          - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"