apiVersion: batch/v1
kind: Job
metadata:
  name: test-k8s-python
spec:
  template:
    spec:
      containers:
        - name: test-k8s-python
          image: culceanluca/test-k8s-python:latest
          imagePullPolicy: Always
      restartPolicy: Never